### ISSUE TITLE
Permissions for backup user.

### ISSUE THREAD

**Issue by Ferada** [omniti-labs/omnipitr#27]
When using `omnipitr-backup-slave` (on 9.3) I initially set up the configuration to use the `replication` user I already had, which only had `replication` permissions. However, I ran into the problem that `pg_stat_file` (or `pg_read_file`) requires `superuser` permissions, even though the process might be able to read the created file regardless.

Would it be possible to circumvent this either by using a command via SSH, or a workaround in SQL?

(Also, awesome tool, thanks a lot!)

**Comment by depesz** [comment]
Well, workaround would be possible, of course, but that's not done simply with a line or two.
Given that every aspect of omnipitr is configurable, we're looking for at least couple of more options to be handled (ssh username/password, or additional host/port/database/username).

What you could try to do, is to create additional user, with its own schema, add to its schema wrapper functions for pg_stat_file and pg_read_file, defined by superuser, with "security definer", and grant your additional user privileges to run these. + replication privileges in pg_hba_conf.

It could work.

**Comment by Ferada** [comment]
Oh cool, thanks for that suggestion, I'll try that. And yeah, I didn't want to suggest that it was a simple fix, however we're a bit uneasy with running this (anything really) with `superuser` permissions, which is why I was asking.

**Comment by depesz** [comment]
Please let me know how it will pan out. To be honest, I'd prefer to avoid adding all these additional options to omnipitr, but if it would be necessary, of course it will have to be done.
