### ISSUE TITLE
Support for logical replication

### ISSUE THREAD

**Issue by aven92** [omniti-labs/omnipitr#29]
Such as the title, when will the omnipitr support to the logical replication?

**Comment by depesz** [comment]
There are no such plans. What exactly would be the role of omnipitr in LR scenario?

**Comment by aven92** [comment]
@depesz  We wanna use it to make daily backup, we use it before the version of 9.4 in the hot_standby mode.

**Comment by depesz** [comment]
I don't see how logical replication is related. From where I stand, replica in logical replication can be backed up just as normal database. no support in omnipitr needed. If i'm wrong - please explain what is omnipitr supposed to do in LR scenario that it doesn't do now.
