### ISSUE TITLE
If using archive_cleanup_command, omnipitr-backup_slave does not work

### ISSUE THREAD

**Issue by keithf4** [omniti-labs/omnipitr#30]
If the archive_cleanup_command is set on a slave to clean up WAL files sent over, then an omnipitr-backup-slave is started, it can get stuck forever waiting for the backup file at the step below because the archive_cleanup_command could have removed it.
```
2015-03-31 23:15:20.193327 +0000 : 11448 : omnipitr-backup-slave : LOG : Waiting for file matching $VAR1 = qr/(?-xism:\A[0-9A-F]{8}0000186400000011\.00000028\.backup\.gz\z)/;
```
Not sure if there's any way to have omnipitr handle not removing the backup file of the WAL destination given in -s parameter to omnipitr-backup-slave if omnipitr-backup-slave is running

**Comment by keithf4** [comment]
Ugh... actually, realized I had the -s option set to the wrong place in the backup command, so it was just sitting there waiting as it should. Still, the archive_cleanup_command did remove the .backup.gz file from the -s location on the slave. Should that be a concern?

**Comment by depesz** [comment]
There is "removal-pause-trigger" option for pausing removal while backup is taken.

As for .backup files - I chose not to delete them, for some reason that I can't recall now. They should be small enough not to cause any problems with disk space usage.

If you think they really have to be removed, well - ping me on IRC.

**Comment by keithf4** [comment]
Completely missed the removal-pause-trigger! Exactly what I needed. Thanks!
