### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PSUdaemon** [omniti-labs/omnipitr#35]
What license are you distributing this under?

**Comment by keithf4** [comment]
License is in the doc folder. Looks to be identical to the PostgreSQL license except "the author" is explicitly named as OmniTI

**Comment by PSUdaemon** [comment]
Usually licenses are placed in a file called `LICENSE` in the root or mentioned in the `README` or both. Would you accept a PR for this?

**Comment by keithf4** [comment]
Payal put a link to the license in the README. That work?

**Comment by PSUdaemon** [comment]
Thanks.
