### ISSUE TITLE
 pg_log and pg_xlog in omnipitr/doc/changes.pod should be changed

### ISSUE THREAD

**Issue by lihailong** [omniti-labs/omnipitr#38]
Please help me to change it, thxs.

**Comment by depesz** [comment]
Where in the file it should be changed, and why?

**Comment by lihailong** [comment]
I am so sorry!  It is in the file omnipitr/doc/changes.pod, and it is just a change log of committed on 2010-06-28.

**Comment by lihailong** [comment]
I mistakenly thought it should be changed to log and pg_wal just like other changes in order to work with PostgreSQL 10.
