### ISSUE TITLE
Unable to successfully run omnipitr-restore.

### ISSUE THREAD

**Issue by tanveerg** [omniti-labs/omnipitr#39]
Hi, 
I am fairly new (actually very new) to omnipitr. I am trying to restore a backup that was taken via omnipitr-backup. Command for backup is something like this - 
```
omnipitr-backup-slave \
 --data-dir <PATH_TO_DATA_DIRECTORY> \
 --dst-local <PATH_TO_LOCAL_DESTINATION> \
 --host <HOST_IP> \
 --log <PATH_TO_LOG_OUTPUT> \
 --pgcontroldata-path <PATH_TO_PGCONTROLDATA> \
 --port <PORT> \
 --pid-file <PATH_TO_PID_FILE> \
 --removal-pause-trigger<PATH_TO_REMOVAL_PAUSE_TRIGGER> \
 --source gzip=<PATH_TO_SOURCE> \
 --temp-dir <PATH_TO_TEMP_DIR> \
 --call-master \
 --digest SHA-1 \
 --gzip-path <PATH_TO_PIGZ> \
 --not-nice \
 --parallel-jobs 10 \
 --verbose
```

The backup was taken successfully. I am trying to restore this on another server running postgres. And I am trying to run this command:
```
omnipitr-restore \
--data-dir <PATH_TO_DATA_DIRECTORY> \
--source gzip=<PATH_TO_SOURCE> \
--log <PATH_TO_LOG_OUTPUT> \
--gzip-path <PATH_TO_PIGZ> \
--remove-unneeded \
--verbose
```
However, running the command above gives me this error - 
`omnipitr-restore : FATAL : WAL segment file name and/or destination have not been given`
I tried looking through the source code for omnipitr-restore too but unfortunately I am not proficient in perl that much so it wasn't obvious to me what might be going on. That being said, I have a hunch I am trying to pass in wrong command line arguments over here but I have tried to follow the documentation as much as possible. Any help would be appreciated. 
I believe the version of omnipitr is 1.3.2.

**Comment by depesz** [comment]
omnipitr-restore is not for restoring backups - this is done by simply unpacking the archive. omnipitr-restore is to be used as "restore_command" in recovery.conf.
